# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile CXX with /usr/bin/c++
CXX_FLAGS =  -arch i386 -isysroot /Developer/SDKs/MacOSX10.6.sdk -I/Users/diederickhuijbers/of/addons_diederick/ofxKeylogger/libs/mac/include  

CXX_DEFINES = 

